-- MySQL Script generated by MySQL Workbench
-- Tue Jun 26 20:52:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema life-guru
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `life-guru` ;

-- -----------------------------------------------------
-- Schema life-guru
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `life-guru` DEFAULT CHARACTER SET utf8 ;
USE `life-guru` ;

-- -----------------------------------------------------
-- Table `life-guru`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `life-guru`.`users` ;

CREATE TABLE IF NOT EXISTS `life-guru`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `experiencePoints` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `life-guru`.`achievements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `life-guru`.`achievements` ;

CREATE TABLE IF NOT EXISTS `life-guru`.`achievements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(45) NULL,
  `experiencePoints` INT NOT NULL,
  `type` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `life-guru`.`users_has_achievements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `life-guru`.`users_has_achievements` ;

CREATE TABLE IF NOT EXISTS `life-guru`.`users_has_achievements` (
  `users_id` INT NOT NULL,
  `achievements_id` INT NOT NULL,
  `imagePath` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`users_id`, `achievements_id`),
  INDEX `fk_users_has_achievements_achievements1_idx` (`achievements_id` ASC),
  INDEX `fk_users_has_achievements_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_achievements_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `life-guru`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_achievements_achievements1`
    FOREIGN KEY (`achievements_id`)
    REFERENCES `life-guru`.`achievements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
